project_id = "itlaebjtakhcpioloaun"

[functions.submit-order]
verify_jwt = false

[functions.upload-order-file]
verify_jwt = false

[functions.send-order-received]
verify_jwt = false

[functions.download-file]
verify_jwt = false
